- hosts: K8s_nodes
  become: true
  tasks:
    - name: Edit module configs
      ansible.builtin.lineinfile:
        path: "/etc/modules-load.d/k8s.conf"
        line: '{{ item }}'
        create: true
        mode: '0644'
      loop:
        - overlay
        - br_netfilter

    - name: Add modules
      community.general.modprobe:
        name: '{{ item }}'
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: sysctl params required by setup, params persist across reboots
      ansible.posix.sysctl:
        sysctl_file: /etc/sysctl.d/k8s.conf
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
        reload: true
      loop:
        - name: 'net.bridge.bridge-nf-call-iptables'
          value: '1'
        - name: 'net.bridge.bridge-nf-call-ip6tables'
          value: '1'
        - name: 'net.ipv4.ip_forward'
          value: '1'
      # notify: Apply sysctl params without reboot

  # handlers:
  #   - name: Apply sysctl params without reboot
  #     ansible.builtin.command: sysctl --system

    